Feature c
chinweokwu/netweb_responsive pull request #2
Opened 2020-02-28 18:08 UTC by chinweokwu

This is a responsive web design project, we will use html and css principles to make a site like TNW homepage. This project has 3 break point as specified by microverse. we also used flex and grid for this project.

2020-02-28 18:29 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-02-28 19:28 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
## Required Changes:
#### General 
- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history
- [x] Pull Request has meaningful title 
#### Latest news section
###### Small version changes
- [ ] The images are a bit big compared to original
### Original
![1](https://user-images.githubusercontent.com/23278161/75579890-07f74b80-5a67-11ea-87c5-0a0cc3237fa5.png)
### Yours
![3](https://user-images.githubusercontent.com/23278161/75580721-8bfe0300-5a68-11ea-93eb-29df7a4b5d6c.png)



#### Latest deals section
###### Small version changes
- [ ] The images are a bit big compared to original
### Original

![2](https://user-images.githubusercontent.com/23278161/75580689-80124100-5a68-11ea-8ed4-bae454acc509.png)

### Yours
![4](https://user-images.githubusercontent.com/23278161/75580625-65d86300-5a68-11ea-8022-20249545480d.png)


##### Footer
* [x] It contains social media icons vertically and horizontally aligned
- [x] Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)
### Make changes and submit another code review request.
*Happy coding*

2020-02-28 19:29 UTC, kobiyoyo commented on css/mediaquery.css
> +    display: block;
Elements should be aligned with float and flex or grid

2020-02-28 23:36 UTC, uryelah commented
Hello **Mauricio Santos Hoyos** & **Morah Morah**, I'm Sarah, your reviewer for this PR .

You did a great job implementing the required changes from the last review.
Congratulations the project is very responsive! 🥇 

The project is almost good to be approved, you just need to fix a little text spacing issue on small screens.

-------

### Required Changes

- [ ]  The text at the bottom of the main sections, starting from apps, has some margin in the original site. Check the comparison between your project and the original site bellow.

Your version:
![Screenshot_2020-02-28 Page Title](https://user-images.githubusercontent.com/16193212/75595070-bb613f80-5a69-11ea-8e93-971ae5a43890.png)

Original site:
![Screenshot_2020-02-28 TNW - International technology news, business and culture(4)](https://user-images.githubusercontent.com/16193212/75595071-bd2b0300-5a69-11ea-8524-5609cc8b210b.png)

-------

**Kindly implement the changes above and request a new code review.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-02-29 01:01 UTC, SofiBretz commented
Code under review by SofiBretz. Thanks!✨

2020-02-29 01:18 UTC, SofiBretz commented
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Consider resize the images as the original page, on the 'Latest Deals' and on 'Latest News' and add a margin between texts.

![1](https://user-images.githubusercontent.com/42303392/75597956-409f2100-5a77-11ea-8b70-f2567fd812c8.PNG)

![1 2](https://user-images.githubusercontent.com/42303392/75597959-439a1180-5a77-11ea-9017-ede767e0cf6c.PNG)

- [ ] Consider follow the design as the original page, the decoration orange circles have to be inline with the text. 

![2](https://user-images.githubusercontent.com/42303392/75597976-65939400-5a77-11ea-83fa-7685bac101fb.PNG)

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

[OPTIONAL]

- [ ] Consider adding the demo link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

2020-03-02 12:38 UTC, lekegitrepo commented
This **PR** is under Review by **_[TSE] Temitayo Adeleke_**

2020-03-02 13:15 UTC, lekegitrepo commented
### Hi Team,
You have done an excellent job. **_This is approved_** base on making the required changes stipulated by the previous reviewer.

**_However, you can check the images below to improve the page responsiveness at 768px and below breakpoints_**

## Optional:

**_This is your page at 768px:_**

![image](https://user-images.githubusercontent.com/48312803/75678972-603f7080-5c54-11ea-95fa-18ec396913b2.png)

**_This is the original at 768px:_**

![image](https://user-images.githubusercontent.com/48312803/75679073-8c5af180-5c54-11ea-8dac-4b29c417038c.png)

**_This is your page responsive below 768px:_**

![image](https://user-images.githubusercontent.com/48312803/75679292-f1aee280-5c54-11ea-8d4e-8d7d101bcfcc.png)

**_This is the original:_**

![image](https://user-images.githubusercontent.com/48312803/75679326-0a1efd00-5c55-11ea-9bca-9343ec190bd4.png)

Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

2020-03-02 13:17 UTC, lekegitrepo approved these changes
## Status: Approved.

2021-01-30 00:17 UTC, merged